### ISSUE TITLE
Build fails when using a component

### ISSUE THREAD

**Issue by milkyskies** [RafidMuhymin/astro-imagetools#113]
Hi, I'm trying to use this plugin, and I'm getting the following error message on build when trying to import the components.
```
 error   Named export 'findUp' not found. The requested module 'find-up' is a CommonJS module, which may not support all module.exports as named exports.
  CommonJS modules can always be imported via the default export, for example using:
  
  import pkg from 'find-up';
  const { findUp } = pkg;
  
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:541:24)
    at async generatePages (file:///home/milkyskies/projects/rcc-astro/node_modules/astro/dist/core/build/generate.js:70:20)
    at async staticBuild (file:///home/milkyskies/projects/rcc-astro/node_modules/astro/dist/core/build/static-build.js:68:7)
    at async AstroBuilder.build (file:///home/milkyskies/projects/rcc-astro/node_modules/astro/dist/core/build/index.js:83:5)
    at async AstroBuilder.run (file:///home/milkyskies/projects/rcc-astro/node_modules/astro/dist/core/build/index.js:123:7)
    at async build (file:///home/milkyskies/projects/rcc-astro/node_modules/astro/dist/core/build/index.js:22:3)
    at async runCommand (file:///home/milkyskies/projects/rcc-astro/node_modules/astro/dist/cli/index.js:138:14)
```

I also get `Cannot find module 'astro-imagetools/components' or its corresponding type declarations.` on the editor.

Using astro 1.0.6 and astro-imagetools 0.6.10.

**Comment by milkyskies** [comment]
Sorry, it was a duplicate issue.
