### ISSUE TITLE
Build not working

### ISSUE THREAD

**Issue by KyleFontenot** [RafidMuhymin/astro-imagetools#15]
Build mode is erroring out for me.

The Image import alone throws the error: `import Image from "astro-imagetools";` with or without including it in the component. I've updated to all latest node packages, experimental flag gives same error, and it works fine in dev mode. Have no idea how to troubleshoot.

Error:
```
'createHash' is not exported by __vite-browser-external, imported by node_modules/imagetools-core/dist/index.mjs
file: /home/kyle/Software/CarbideSawTool/node_modules/imagetools-core/dist/index.mjs:2:9
1: import sharp from 'sharp';
2: import { createHash } from 'crypto';
            ^
3: 
4: const METADATA = Symbol('image metadata');
Error: 'createHash' is not exported by __vite-browser-external, imported by node_modules/imagetools-core/dist/index.mjs
    at error (/home/kyle/Software/CarbideSawTool/node_modules/rollup/dist/shared/rollup.js:198:30)
    at Module.error (/home/kyle/Software/CarbideSawTool/node_modules/rollup/dist/shared/rollup.js:12477:16)
    at Module.traceVariable (/home/kyle/Software/CarbideSawTool/node_modules/rollup/dist/shared/rollup.js:12835:29)
```

**Comment by KyleFontenot** [comment]
Magically started working when I was narrowing down the issue compared to a recreation. Maybe having to do with the cache
