### ISSUE TITLE
Errors on build/dev

### ISSUE THREAD

**Issue by preetamslot** [RafidMuhymin/astro-imagetools#2]
node: 16.13.0 (Currently using 64-bit executable)
npm: 8.1.0
Windows 10
```
> astro dev --verbose

  astro:cli --verbose flag enabled! Enabling: DEBUG="*,-babel" +0ms
  astro:cli Tip: Set the DEBUG env variable directly for more control. Example: "DEBUG=astro:*,vite:* astro build". +3ms
 > node_modules/@astropub/codecs/dist/codecs.js:7:34: error: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
    7 │ const fetch = globalThis.fetch || await import('@astropub/webapi').then(webapi => webapi.fetch, (... 
      ╵                                   ~~~~~

 > node_modules/@astropub/codecs/dist/codecs.js:1:25: error: Could not resolve "node:process" (mark it as external to exclude it from the bundle)
    1 │ import * as process from 'node:process'
      ╵                          ~~~~~~~~~~~~~~

 > node_modules/@astropub/codecs/dist/codecs.js:7:109: error: Could not resolve "node:fs/promises" (mark it as external to exclude it from the bundle, or add ".catch()" to handle the failure at run-time)
    7 │ ...mport('@astropub/webapi').then(webapi => webapi.fetch, () => import('node:fs/promises').readFile) 
      ╵                                                                        ~~~~~~~~~~~~~~~~~~

 > node_modules/@astropub/codecs/dist/avif/thread.js:1:24: error: Could not resolve "node:worker_threads" (mark it as external to exclude it from the bundle)
    1 │ import * as thread from 'node:worker_threads'
      ╵                         ~~~~~~~~~~~~~~~~~~~~~

 > node_modules/@astropub/codecs/dist/transform/blurhash/thread.js:1:24: error: Could not resolve "node:worker_threads" (mark it as external to exclude it from the bundle)
    1 │ import * as thread from 'node:worker_threads'
      ╵                         ~~~~~~~~~~~~~~~~~~~~~

 > node_modules/@astropub/codecs/dist/wp2/thread.js:1:24: error: Could not resolve "node:worker_threads" (mark it as external to exclude it from the bundle)
    1 │ import * as thread from 'node:worker_threads'
      ╵                         ~~~~~~~~~~~~~~~~~~~~~

 > node_modules/@astropub/codecs/dist/png/thread.js:1:24: error: Could not resolve "node:worker_threads" (mark it as external to exclude it from the bundle)
    1 │ import * as thread from 'node:worker_threads'
      ╵                         ~~~~~~~~~~~~~~~~~~~~~

 > node_modules/@astropub/codecs/dist/jpg/thread.js:1:24: error: Could not resolve "node:worker_threads" (mark it as external to exclude it from the bundle)
    1 │ import * as thread from 'node:worker_threads'
      ╵                         ~~~~~~~~~~~~~~~~~~~~~

 > node_modules/@astropub/codecs/dist/webp/thread.js:1:24: error: Could not resolve "node:worker_threads" (mark it as external to exclude it from the bundle)
    1 │ import * as thread from 'node:worker_threads'
      ╵                         ~~~~~~~~~~~~~~~~~~~~~

 > node_modules/@astropub/codecs/dist/jxl/thread.js:1:24: error: Could not resolve "node:worker_threads" (mark it as external to exclude it from the bundle)
    1 │ import * as thread from 'node:worker_threads'
      ╵                         ~~~~~~~~~~~~~~~~~~~~~

 > node_modules/@astropub/codecs/dist/avif/codec.js:16:19: error: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
    16 │ const wasmDecode = await esmDecode.ready.then(exports => exports.decode)
       ╵                    ~~~~~

 > node_modules/@astropub/codecs/dist/transform/blur/thread.js:1:24: error: Could not resolve "node:worker_threads" (mark it as external to exclude it from the bundle)
    1 │ import * as thread from 'node:worker_threads'
      ╵                         ~~~~~~~~~~~~~~~~~~~~~

 > node_modules/@astropub/codecs/dist/transform/resize/thread.js:1:24: error: Could not resolve "node:worker_threads" (mark it as external to exclude it from the bundle)
    1 │ import * as thread from 'node:worker_threads'
      ╵                         ~~~~~~~~~~~~~~~~~~~~~

 > node_modules/@astropub/codecs/dist/png/codec.js:5:19: error: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
    5 │ const encdecWasm = await readFile(new URL('./png-enc-dec.wasm', import.meta.url))
      ╵                    ~~~~~

 > node_modules/@astropub/webapi/mod.js:1:75: error: Could not resolve "node:timers" (mark it as external to 
exclude it from the bundle)
    1 │ import { setTimeout as setTimeout$1, clearTimeout as clearTimeout$1 } from 'node:timers';
      ╵                                                                            ~~~~~~~~~~~~~

 > node_modules/@astropub/codecs/dist/avif/codec.js:17:19: error: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
    17 │ const wasmEncode = await esmEncode.ready.then(exports => exports.encode)
       ╵                    ~~~~~

 > node_modules/@astropub/codecs/dist/jxl/codec.js:16:19: error: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
    16 │ const wasmDecode = await esmDecode.ready.then(exports => exports.decode)
       ╵                    ~~~~~

 > node_modules/@astropub/codecs/dist/jxl/codec.js:17:19: error: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
    17 │ const wasmEncode = await esmEncode.ready.then(exports => exports.encode)
       ╵                    ~~~~~

 > node_modules/@astropub/codecs/dist/transform/resize/codec.js:6:16: error: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
    6 │ const asmData = await readFile(asmPath)
      ╵                 ~~~~~

 > node_modules/@astropub/codecs/dist/wp2/codec.js:16:19: error: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
    16 │ const wasmDecode = await esmDecode.ready.then(exports => exports.decode)
       ╵                    ~~~~~

 > node_modules/@astropub/codecs/dist/jpg/codec.js:16:19: error: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
    16 │ const wasmDecode = await esmDecode.ready.then(exports => exports.decode)
       ╵                    ~~~~~

 > node_modules/@astropub/codecs/dist/png/codec.js:6:21: error: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
    6 │ const optimizeWasm = await readFile(new URL('./png-optimize.wasm', import.meta.url))
      ╵                      ~~~~~

 > node_modules/@astropub/codecs/dist/webp/codec.js:16:19: error: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
    16 │ const wasmDecode = await esmDecode.ready.then(exports => exports.decode)
       ╵                    ~~~~~

 > node_modules/@astropub/codecs/dist/transform/resize/codec.js:8:0: error: Top-level await is not available 
in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
    8 │ await codec.default(asmData)
      ╵ ~~~~~

 > node_modules/@astropub/codecs/dist/wp2/codec.js:17:19: error: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
    17 │ const wasmEncode = await esmEncode.ready.then(exports => exports.encode)
       ╵                    ~~~~~

 > node_modules/@astropub/codecs/dist/jpg/codec.js:17:19: error: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
    17 │ const wasmEncode = await esmEncode.ready.then(exports => exports.encode)
       ╵                    ~~~~~

 > node_modules/@astropub/codecs/dist/webp/codec.js:17:19: error: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
    17 │ const wasmEncode = await esmEncode.ready.then(exports => exports.encode)
       ╵                    ~~~~~

 > node_modules/@astropub/codecs/dist/png/codec.js:8:0: error: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
    8 │ await encdec.default(encdecWasm)
      ╵ ~~~~~

 > node_modules/@astropub/codecs/dist/png/codec.js:9:0: error: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
    9 │ await optimize.default(optimizeWasm)
      ╵ ~~~~~

 > node_modules/@astropub/webapi/mod.js:2:17: error: Could not resolve "node:http" (mark it as external to exclude it from the bundle)
    2 │ import http from 'node:http';
      ╵                  ~~~~~~~~~~~

 > node_modules/@astropub/codecs/dist/avif/codec.js:1:29: error: Could not resolve "node:fs" (mark it as external to exclude it from the bundle)
    1 │ import { readFileSync } from 'node:fs'
      ╵                              ~~~~~~~~~

 > node_modules/@astropub/codecs/dist/jxl/codec.js:1:29: error: Could not resolve "node:fs" (mark it as external to exclude it from the bundle)
    1 │ import { readFileSync } from 'node:fs'
      ╵                              ~~~~~~~~~

 > node_modules/@astropub/codecs/dist/png/codec.js:1:25: error: Could not resolve "node:fs/promises" (mark it as external to exclude it from the bundle)
    1 │ import { readFile } from 'node:fs/promises'
      ╵                          ~~~~~~~~~~~~~~~~~~

 > node_modules/@astropub/codecs/dist/transform/resize/codec.js:2:25: error: Could not resolve "node:fs/promises" (mark it as external to exclude it from the bundle)
    2 │ import { readFile } from 'node:fs/promises'
      ╵                          ~~~~~~~~~~~~~~~~~~

 > node_modules/@astropub/codecs/dist/wp2/codec.js:1:29: error: Could not resolve "node:fs" (mark it as external to exclude it from the bundle)
    1 │ import { readFileSync } from 'node:fs'
      ╵                              ~~~~~~~~~

 > node_modules/@astropub/codecs/dist/webp/codec.js:1:29: error: Could not resolve "node:fs" (mark it as external to exclude it from the bundle)
    1 │ import { readFileSync } from 'node:fs'
      ╵                              ~~~~~~~~~

 > node_modules/@astropub/codecs/dist/jpg/codec.js:1:29: error: Could not resolve "node:fs" (mark it as external to exclude it from the bundle)
    1 │ import { readFileSync } from 'node:fs'
      ╵                              ~~~~~~~~~

 > node_modules/@astropub/webapi/mod.js:3:18: error: Could not resolve "node:https" (mark it as external to exclude it from the bundle)
    3 │ import https from 'node:https';
      ╵                   ~~~~~~~~~~~~

 > node_modules/@astropub/webapi/mod.js:4:17: error: Could not resolve "node:zlib" (mark it as external to exclude it from the bundle)
    4 │ import zlib from 'node:zlib';
      ╵                  ~~~~~~~~~~~

 > node_modules/@astropub/webapi/mod.js:5:60: error: Could not resolve "node:stream" (mark it as external to 
exclude it from the bundle)
    5 │ import Stream, { PassThrough, pipeline as pipeline$1 } from 'node:stream';
      ╵                                                             ~~~~~~~~~~~~~

 > node_modules/@astropub/webapi/mod.js:6:44: error: Could not resolve "node:util" (mark it as external to exclude it from the bundle)
    6 │ import { promisify, deprecate, types } from 'node:util';
      ╵                                             ~~~~~~~~~~~

 > node_modules/@astropub/webapi/mod.js:7:35: error: Could not resolve "node:url" (mark it as external to exclude it from the bundle)
    7 │ import { format as format$1 } from 'node:url';
      ╵                                    ~~~~~~~~~~

 > node_modules/@astropub/webapi/mod.js:8:21: error: Could not resolve "node:net" (mark it as external to exclude it from the bundle)
    8 │ import { isIP } from 'node:net';
      ╵                      ~~~~~~~~~~

 > node_modules/@astropub/webapi/mod.js:9:28: error: Could not resolve "node:perf_hooks" (mark it as external to exclude it from the bundle)
    9 │ import { performance } from 'node:perf_hooks';
      ╵                             ~~~~~~~~~~~~~~~~~

 > node_modules/@astropub/webapi/mod.js:7844:26: error: Could not resolve "node:fs" (mark it as external to exclude it from the bundle, or add ".catch()" to handle the failure at run-time)
    7844 │             return import('node:fs').then(fs => {
         ╵                           ~~~~~~~~~

Error: Build failed with 45 errors:
node_modules/@astropub/codecs/dist/avif/codec.js:1:29: error: Could not resolve "node:fs" (mark it as external to exclude it from the bundle)
node_modules/@astropub/codecs/dist/avif/codec.js:16:19: error: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
node_modules/@astropub/codecs/dist/avif/codec.js:17:19: error: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
node_modules/@astropub/codecs/dist/avif/thread.js:1:24: error: Could not resolve "node:worker_threads" (mark 
it as external to exclude it from the bundle)
node_modules/@astropub/codecs/dist/codecs.js:1:25: error: Could not resolve "node:process" (mark it as external to exclude it from the bundle)
...
    at failureErrorWithLog (C:\SITES\bliss-astro-netlify\node_modules\esbuild\lib\main.js:1493:15)
    at C:\SITES\bliss-astro-netlify\node_modules\esbuild\lib\main.js:1151:28
    at runOnEndCallbacks (C:\SITES\bliss-astro-netlify\node_modules\esbuild\lib\main.js:941:63)
    at buildResponseToResult (C:\SITES\bliss-astro-netlify\node_modules\esbuild\lib\main.js:1149:7)
    at C:\SITES\bliss-astro-netlify\node_modules\esbuild\lib\main.js:1258:14
    at C:\SITES\bliss-astro-netlify\node_modules\esbuild\lib\main.js:629:9
    at handleIncomingPacket (C:\SITES\bliss-astro-netlify\node_modules\esbuild\lib\main.js:726:9)
    at Socket.readFromStdout (C:\SITES\bliss-astro-netlify\node_modules\esbuild\lib\main.js:596:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command npm run start" terminated with exit code: 1.
```

**Comment by RafidMuhymin** [comment]
Sorry @preetamslot that you have faced the issue. Actually, I made a mistake when writing the README. I have updated the following section. I hope that it'll fix this issue.
![image](https://user-images.githubusercontent.com/63650415/153709193-fc9bb4f5-69fd-4e4a-87d7-8da9fe628fdc.png)

**Comment by RafidMuhymin** [comment]
@preetamslot Starting from `v0.0.9`, the plugin now automatically excludes the necessary dependencies from being prebuilt and SSR.

**Comment by heliokroger** [comment]
Sorry for reopening the issue, but the solution that @RafidMuhymin provided led me to another issue. My `astro.config.mjs` is:
```
import { defineConfig } from "astro/config";

// https://astro.build/config
import image from "@astrojs/image";

// https://astro.build/config
import compress from "astro-compress";

// https://astro.build/config
import critters from "astro-critters";

import { astroImageTools } from "astro-imagetools";
import astroImagePlugin from "astro-imagetools/plugin";

// https://astro.build/config
export default defineConfig({
  integrations: [
    image({
      serviceEntryPoint: "@astrojs/image/sharp",
    }),
    astroImageTools,
    critters(),
    compress(),
  ],
  vite: {
    plugins: [astroImagePlugin],
    optimizeDeps: {
      exclude: ["@astropub/codecs", "imagetools-core", "sharp"],
    },
    ssr: {
      external: ["sharp", "potrace"],
    },
  },
});
```
And when I try to build it:
```
$ astro build
09:44:21 AM [astro] Unable to load /Users/heliokroger/projects/blog/astro.config.mjs

 error   Missing "./plugin" specifier in "astro-imagetools" package
  File:
    /Users/heliokroger/projects/blog/astro.config.mjs
```
