### ISSUE TITLE
BackgroundImage component error with alt tag

### ISSUE THREAD

**Issue by bronze** [RafidMuhymin/astro-imagetools#35]
Hi there, was doing a little experiment setting up demos of the new components and i believe i found a bug
 The `<BackgroundImage>` component throws a 500 error if we leave the "alt" tag.
I saw your recent commit with a demo and compared it to what i was doing, and removing the alt solves it ([link to the offending line](https://github.com/bronze/astro-image-demo/blob/ad2f04ae23051bb4f6ee0659a42613b000bb3816/src/pages/backgroundimage.astro#L16)).

here's the error:
```
Cannot read properties of undefined (reading 'map')

TypeError: Cannot read properties of undefined (reading 'map')
    at /node_modules/astro-imagetools/api/renderBackgroundImage.js:106:16
    at Array.map (<anonymous>)
    at /node_modules/astro-imagetools/api/renderBackgroundImage.js:102:12
    at Array.map (<anonymous>)
    at Module.renderBackgroundImage [as default] (/node_modules/astro-imagetools/api/renderBackgroundImage.js:75:8)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async eval (/home/bronze/coding/astro-image-demo/node_modules/astro-imagetools/components/BackgroundImage.astro:4:0)
    at async renderToString (/node_modules/astro/dist/runtime/server/index.js:330:21)
    at async Module.renderComponent (/node_modules/astro/dist/runtime/server/index.js:125:20)
```

**Comment by RafidMuhymin** [comment]
Thanks @bronze for reporting and glad to hear you have already figured it out. Closing this issue as the docs have been updated.
