### ISSUE TITLE
`line` must be greater than 0

### ISSUE THREAD

**Issue by IanVS** [RafidMuhymin/astro-imagetools#47]
I tried to use `<Picture/>` in my Astro 1.0.0-beta.24 project, and got this error:

```
4:23:43 PM [vite] Error when evaluating SSR module /node_modules/object-hash/index.js?v=a4b9ea0a:
ReferenceError: require is not defined
    at /node_modules/object-hash/index.js?v=a4b9ea0a:3:14
    at instantiateModule (/Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:59322:15)
4:23:43 PM [vite] Error when evaluating SSR module /node_modules/astro-imagetools/api/utils/getImage.js:
ReferenceError: require is not defined
    at /node_modules/object-hash/index.js?v=a4b9ea0a:1:13
    at instantiateModule (/Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:59322:15)
4:23:43 PM [vite] Error when evaluating SSR module /node_modules/astro-imagetools/components/Img.astro:
Error: `line` must be greater than 0 (lines start at line 1)
    at originalPositionFor$1 (/Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:1780:19)
    at /Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:59112:25
    at String.replace (<anonymous>)
    at /Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:59102:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (/Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:59101:10)
    at instantiateModule (/Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:59327:32)
4:23:43 PM [vite] Error when evaluating SSR module /node_modules/astro-imagetools/components/index.js?v=a4b9ea0a:
Error: `line` must be greater than 0 (lines start at line 1)
    at originalPositionFor$1 (/Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:1780:19)
    at /Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:59112:25
    at String.replace (<anonymous>)
    at /Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:59102:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (/Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:59101:10)
    at instantiateModule (/Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:59327:32)
4:23:43 PM [vite] Error when evaluating SSR module /src/components/screens/blog/Hero.astro:
Error: `line` must be greater than 0 (lines start at line 1)
    at originalPositionFor$1 (/Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:1780:19)
    at /Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:59112:25
    at String.replace (<anonymous>)
    at /Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:59102:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (/Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:59101:10)
    at instantiateModule (/Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:59327:32)
4:23:43 PM [vite] Error when evaluating SSR module /src/layouts/BlogPost.astro:
Error: `line` must be greater than 0 (lines start at line 1)
    at originalPositionFor$1 (/Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:1780:19)
    at /Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:59112:25
    at String.replace (<anonymous>)
    at /Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:59102:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (/Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:59101:10)
    at instantiateModule (/Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:59327:32)
4:23:43 PM [vite] Error when evaluating SSR module /Users/ianvs/code/defined/www/src/pages/blog/[...page].astro:
Error: `line` must be greater than 0 (lines start at line 1)
    at originalPositionFor$1 (/Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:1780:19)
    at /Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:59112:25
    at String.replace (<anonymous>)
    at /Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:59102:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (/Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:59101:10)
    at instantiateModule (/Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:59327:32)
 error   `line` must be greater than 0 (lines start at line 1)
    at originalPositionFor$1 (/Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:1780:19)
    at /Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:59112:25
    at String.replace (<anonymous>)
    at /Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:59102:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (/Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:59101:10)
    at instantiateModule (/Users/ianvs/code/defined/www/node_modules/vite/dist/node/chunks/dep-88bd5805.js:59327:32)
```

Here's a reproduction: https://stackblitz.com/edit/github-bvrynd?file=src/pages/index.astro

**Comment by ClintH** [comment]
That seems to happen if astro-imagetools is not added to `astro.config.mjs`.

Eg:

```
import {defineConfig} from 'astro/config';
import preact from '@astrojs/preact';
import {astroImageTools} from "astro-imagetools";
import react from "@astrojs/react";

// https://astro.build/config
export default defineConfig({
  integrations: [preact(), react(), astroImageTools]
});
```

**Comment by IanVS** [comment]
I see, thanks.  I guess that https://astro-imagetools-docs.netlify.app/en/installation/ is just outdated.

**Comment by IanVS** [comment]
Ah, the docs file has been updated, but it hasn't been deployed.

**Comment by IanVS** [comment]
The docs are deployed now.

**Comment by ericjeker** [comment]
For the people wondering, I had to use the config from the demo for the integration to work:

```javascript
import { defineConfig } from "astro/config";
import { astroImageTools } from "astro-imagetools";

// https://astro.build/config
export default defineConfig({
  vite: {
    plugins: [
      {
        name: "import.meta.url-transformer",
        transform: (code, id) => {
          if (id.endsWith(".astro"))
            return code.replace(/import.meta.url/g, `"${id}"`);
        },
      },
    ],
  },

  experimental: {
    integrations: true,
  },

  integrations: [astroImageTools],
});
```
