### ISSUE TITLE
Unexpected Token

### ISSUE THREAD

**Issue by rnwolf** [RafidMuhymin/astro-imagetools#7]
I get the following 500 error.

'''
Parse failure: Unexpected token (49:8)
Contents of line 49:       ""2022-02-15T10:23:36.821Z"": JSON.stringify(new Date().toISOString()),

Error: Parse failure: Unexpected token (49:8)
Contents of line 49:       ""2022-02-15T10:23:36.821Z"": JSON.stringify(new Date().toISOString()),
    at ssrTransform (C:\Users\rnwol\workspace\astro-throughputfocus-com\node_modules\vite\dist\node\chunks\dep-3d5f2596.js:52118:15)
    at doTransform (C:\Users\rnwol\workspace\astro-throughputfocus-com\node_modules\vite\dist\node\chunks\dep-3d5f2596.js:53035:48)
'''

Using:
"astro": "^0.23.0-next.6",
"astro-imagetools": "^0.0.16",

On MS-Windows 10

![Screenshot 2022-02-15 103319](https://user-images.githubusercontent.com/117415/154044518-919d0e1d-7d37-4d77-992d-fd5d9833d688.png)

**Comment by rnwolf** [comment]
I have gone through the process of setting it up from scratch with
    
"astro": "^0.23.0-next.10",
 "astro-imagetools": "^0.0.16"

And the example you have provided works as expected.  I will retry with my previous site, but we can mark this as closed.
