### ISSUE TITLE
Build error on netlify when image component is in vue slot

### ISSUE THREAD

**Issue by preetamslot** [RafidMuhymin/astro-imagetools#8]
If I import a Vue component for my carousel wrap and nest the image component, I get a build error on Netlify. Local the build runs without error. any idea what this could be?
```
<CarouselWrap client:idle>
    {allServices.map((service) => (
      <div class="flex carousel__slide">
        <div class="text-left">
          <Markdown>{service.intro}</Markdown>
          <a href={service.url} class="btn btn-pink">
            {service.title}
          </a>
        </div>

        <div class="gallery-grid">
          {service.gallery[0] && (
            <div >
              <Image
                src={service.gallery[0].thumbnail}
                alt={service.gallery[0].alt}
                breakpoints={[320, 460, 680]}
              />
            </div>
          )}

          {service.gallery[1] && (
            <div>
              <Image
                src={service.gallery[1].thumbnail}
                alt={service.gallery[1].alt}
                breakpoints={[320, 460, 680]}
              />
            </div>
          )}
          
        </div>
      </div>
    ))}
  </CarouselWrap>
```

error on netlify
```
astro:build Vite started   0.9s
11:05:21 AM: wasm://wasm/0027ed9a:1
11:05:21 AM: RuntimeError: null function or function signature mismatch
11:05:21 AM:     at wasm://wasm/0027ed9a:wasm-function[293]:0x13550
11:05:21 AM:     at wasm://wasm/0027ed9a:wasm-function[300]:0x14277
11:05:21 AM:     at Go._resume (file:///opt/build/repo/node_modules/@astrojs/compiler/node/wasm_exec.js:374:28)
11:05:21 AM:     at file:///opt/build/repo/node_modules/@astrojs/compiler/node/wasm_exec.js:384:16
11:05:21 AM:     at new Promise (<anonymous>)
11:05:21 AM:     at syscall/js.valueNew (file:///opt/build/repo/node_modules/@astrojs/compiler/node/wasm_exec.js:274:54)
11:05:21 AM:     at wasm://wasm/0027ed9a:wasm-function[321]:0x155e8
11:05:21 AM:     at wasm://wasm/0027ed9a:wasm-function[825]:0x6e2a0
11:05:21 AM:     at wasm://wasm/0027ed9a:wasm-function[293]:0x13550
11:05:21 AM:     at wasm://wasm/0027ed9a:wasm-function[300]:0x14277
11:05:21 AM: ​
11:05:21 AM: ────────────────────────────────────────────────────────────────
11:05:21 AM:   "build.command" failed                                        
11:05:21 AM: ────────────────────────────────────────────────────────────────
```

**Comment by RafidMuhymin** [comment]
Looking at the error, it doesn't seem that the problem is related to `astro-imagetools`. Does the problem go away if you keep the entire markup as it is now but replace the `<Image />` components with plain text or HTML elements?

**Comment by preetamslot** [comment]
The error only happens when I include the Image component, w/o image component it works fine. For now I just wont use the image component in Vue slots.

**Comment by RafidMuhymin** [comment]
@preetamslot I am not sure if it's because the `<Image />` component is asynchronous.
